<a href="https://colab.research.google.com/github/RomuloAlvernaz/Machine_Learning_Desafio_2/blob/main/ML_Desafio_2_Romulo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/refs/heads/master/winequality-white.csv')

In [11]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  
0         8.8        6  
1         9.5        6  
2        10.1        6  
3         9.9        6  
4         9.9        6  
...       ...      ...  
4893     11.2        6  
4894      9.6        5  
4895      9.4        6  
4896     12.8        7  
4897     11.8        6  

[4898 rows x 12 columns]

In [59]:
from sklearn.preprocessing import LabelEncoder

In [13]:
def classificar_vinho(quality):
    if quality <= 4:
        return 'ruim'
    elif quality <= 6:
        return 'medio'
    else:
        return 'otimo'

In [14]:
df['categoria'] = df['quality'].apply(classificar_vinho)

In [60]:
dados = df.drop(columns=['quality', 'categoria'])
alvo = df['categoria']

In [61]:
from sklearn.model_selection import train_test_split

In [112]:
dados_train, dados_test, alvo_train, alvo_test = train_test_split(dados, alvo, test_size=0.30, random_state=42)

In [113]:
le = LabelEncoder()
alvo_train = le.fit_transform(alvo_train)
alvo_test = le.transform(alvo_test)

In [114]:
dados_train = dados_train / dados_train.max()
dados_test = dados_test / dados_test.max()

In [115]:
model = tf.keras.models.Sequential([
    tf.keras.Input(shape=(dados_train.shape[1],)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(4, activation='softmax')
])

In [116]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [117]:
model.fit(dados_train, alvo_train, epochs=100)

Epoch 1/100
108/108 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7527 - loss: 0.8146
Epoch 2/100
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7431 - loss: 0.6642
Epoch 3/100
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7423 - loss: 0.6389
Epoch 4/100
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7446 - loss: 0.6221
Epoch 5/100
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7604 - loss: 0.5927
Epoch 6/100
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7581 - loss: 0.5895
Epoch 7/100
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7735 - loss: 0.5539
Epoch 8/100
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7510 - loss: 0.5825
Epoch 9/100
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7576 - loss: 0.5770
Epoch 10/100
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.5803
Epoch 11/100
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7714 - loss: 0.5476
Epoch 12/100
108/108 ━━━━━━━━━━━━━━━━━━━━

In [119]:
model.evaluate(dados_test, alvo_test)

46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7337 - loss: 1.5067


[1.4329800605773926, 0.743537425994873]

In [120]:
import numpy as np
from sklearn.metrics import confusion_matrix

previsoes_prob = model.predict(dados_test)

previsoes = np.argmax(previsoes_prob, axis=1)

matrix = confusion_matrix(alvo_test, previsoes)

print(matrix)

46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
[[1077    0   17]
 [ 319    8    2]
 [  39    0    8]]
